version: '2'
services:
  site:
    build:
      context: .
    ports:
      - "3000:3000"
    links:
      - db
      - fs
    volumes:
      - .:/app
    environment:
      - MONGO_HOST: db
      - WEED_HOST: fs

  judge:
    build:
      context: .
    links:
      - db
      - fs
    cap_add:
      - ALL
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    entrypoint: "node /opt/jude/judge/watch.js"
    environment:
      - MONGO_HOST: db
      - WEED_HOST: fs

  db:
    image: mongo

  fs:
    image: carmark/seaweedfs
    command: "server"